export const widgets = {
  onlineDemo: "Online Experience",
  testInput: "Test Input",
  testOutput: "Test Result",
  wordsNumber: "Word Count",
  runTest: "Run Test",
  timeCost: "More inference time",
  liabilityExemption: "The results are generated by artificial intelligence models and do not represent the views, positions or attitudes of the platform. Please use the generated content in a reasonable and friendly manner"
}