image: docker:24.0.6

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

variables:
  CI_USER: $GITLAB_USER
  CI_TOKEN: $GITLAB_USER_TOKEN_HIVEER
  GIT_DEPTH: 100

stages:
  - test
  - build
  - deploy

# 判断是不是正确的project，正确的branch，以及是不是forked repo过来的MR
.if-main-original-repo: &if-main-original-repo
  if: '$CI_COMMIT_REF_NAME == "main" && $CI_PROJECT_ID == "32" && $CI_MERGE_REQUEST_SOURCE_PROJECT_ID == null'

# .if-staging-original-repo: &if-staging-original-repo
#   if: '$CI_COMMIT_REF_NAME == "staging" && $CI_PROJECT_ID == "32" && $CI_MERGE_REQUEST_SOURCE_PROJECT_ID == null'


# production ci/cd
# e.g., v1.0.0
.if-production-tag-build: &if-production-tag-build
  if: '$CI_PROJECT_ID == "32" && $CI_COMMIT_TAG =~ /^v(\d+(?:\.\d+.\d+)*)$/'

staging-main-build:
  stage: build
  services:
    - docker:24.0.6-dind
  tags:
    - linux-medium-amd64
  rules:
    - <<: *if-production-tag-build
  variables:
    # IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  script:
    - docker login $CI_REGISTRY -u $CI_USER -p $CI_TOKEN
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

# prod-tag-build:
#   stage: build
#   services:
#     - docker:24.0.6-dind
#   tags:
#     - linux-medium-amd64
#   rules:
#     - <<: *if-production-tag-build
#   variables:
#     IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
#   script:
#     - docker login $CI_REGISTRY -u $CI_USER -p $CI_TOKEN
#     - docker build -t $IMAGE_TAG .
#     - docker push $IMAGE_TAG

staging-main-deploy:
  stage: deploy
  tags:
    - linux-medium-amd64
  rules:
    - <<: *if-production-tag-build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$OPEN_PORTAL_STAGING_PEM" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $OPEN_PORTAL_STAGING_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - |
        ssh root@$OPEN_PORTAL_STAGING_HOST "/bin/bash -s" << EOT
          export DEPLOY_IMAGE_TAG=$IMAGE_TAG
          cd /root/open_portal/
          docker compose -f docker_compose_staging.yml pull
          docker compose -f docker_compose_staging.yml up -d --force-recreate web
          docker image prune -f
        EOT

# prod-tag-deploy:
#   stage: deploy
#   tags:
#     - linux-medium-amd64
#   rules:
#     - <<: *if-production-tag-build
#   variables:
#     IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
#   before_script:
#     - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
#     - eval $(ssh-agent -s)
#     - echo "$OPEN_PORTAL_STAGING_PEM" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh
#     - ssh-keyscan $OPEN_PORTAL_PRD_HOST >> ~/.ssh/known_hosts
#     - ssh-keyscan $OPEN_PORTAL_PRD_TWO_HOST >> ~/.ssh/known_hosts
#     - chmod 644 ~/.ssh/known_hosts
#   script:
#     - |
#         ssh root@$OPEN_PORTAL_PRD_HOST "/bin/bash -s" << EOT
#           cd /root/open_portal/
#           docker compose -f docker_compose_production.yml pull
#           docker compose -f docker_compose_production.yml up -d --force-recreate web docs
#           docker image prune -f
#         EOT
#     - |
#         ssh root@$OPEN_PORTAL_PRD_TWO_HOST "/bin/bash -s" << EOT
#           cd /root/open_portal/
#           docker compose -f docker_compose_production.yml pull
#           docker compose -f docker_compose_production.yml up -d --force-recreate web docs
#           docker image prune -f
#         EOT
