version: '2.4'

services:
  nginx:
    image: opencsg/csghub-nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/tmpdata:/var/nginx/client_body_temp
    environment:
      - SERVER_DOMAIN=${SERVER_DOMAIN}
    privileged: true
    networks:
      - opencsg
    restart: always

  postgres:
    image: gradescope/postgresql-multiple-databases:14.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "sdfa23Sh!322"
      POSTGRES_MULTIPLE_DATABASES: "starhub_server,gitea"
    ports:
      - "5433:5432"
    networks:
      - opencsg
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  csghub_portal:
    image: opencsg/csghub-portal:v0.7.0
    restart: always
    command: >
      bash -c "bundle exec rails assets:precompile
      && bundle exec rails db:create
      && bundle exec rails db:migrate
      && bundle exec rails db:seed
      && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./log:/myapp/log
    environment:
      DATABASE_URL: postgresql://postgres:sdfa23Sh!322@postgres:5432/open_portal_db
      ASSET_HOST: http://127.0.0.1:3000
      RAILS_MASTER_KEY: 64f15f995b044427e43fe4897370fd66
      RAILS_SERVE_STATIC_FILES: 'false'
      STARHUB_BASE_URL: http://${SERVER_DOMAIN}
      STARHUB_TOKEN: ${HUB_SERVER_API_TOKEN:-c7ab4948c36d6ecdf35fd4582def759ddd820f8899f5ff365ce16d7185cb2f609f3052e15681e931897259872391cbf46d78f4e75763a0a0633ef52abcdc840c}
      BUCKET_NAME: opencsg-portal-storage
      ENDPOINT: http://${SERVER_DOMAIN}:9000
      ACCESS_ID: admin
      ACCESS_SECRET: Password_123
      REGION:  cn-beijing
      ON_PREMISE: true
      FORCE_PATH_STYLE: true
    ports:
      - "3000:3000"
    networks:
      - opencsg
    depends_on:
      - postgres

  csghub_server:
    image: opencsg/csghub-server:v0.7.0
    depends_on:
      - postgres
      - gitea
    environment:
      STARHUB_SERVER_GITSERVER_URL: http://${SERVER_DOMAIN}/gitserver
      STARHUB_SERVER_FRONTEND_URL: http://${SERVER_DOMAIN}
      STARHUB_DATABASE_DSN: postgresql://postgres:sdfa23Sh!322@postgres:5432/starhub_server?sslmode=disable
      STARHUB_DATABASE_TIMEZONE: Asia/Shanghai
      STARHUB_SERVER_GITSERVER_HOST: http://gitea:3001
      STARHUB_SERVER_GITSERVER_USERNAME: root
      STARHUB_SERVER_GITSERVER_PASSWORD: password123
      STARHUB_SERVER_GITSERVER_WEBHOOK_URL: http://csghub_server:8080/api/v1/callback/git
      GITEA_USERNAME: root
      GITEA_PASSWORD: password123
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sdfa23Sh!322
      POSTGRES_DB: starhub_server
      GIN_MODE: release
      STARHUB_SERVER_API_TOKEN: ${HUB_SERVER_API_TOKEN:-c7ab4948c36d6ecdf35fd4582def759ddd820f8899f5ff365ce16d7185cb2f609f3052e15681e931897259872391cbf46d78f4e75763a0a0633ef52abcdc840c}
      STARHUB_SERVER_S3_ACCESS_KEY_ID: admin
      STARHUB_SERVER_S3_ACCESS_KEY_SECRET: Password_123
      STARHUB_SERVER_S3_ENDPOINT: minio:9000 # used to generate download links for lfs files
      STARHUB_SERVER_S3_BUCKET: opencsg-server-lfs
      STARHUB_SERVER_S3_REGION: cn-beijing
      STARHUB_SERVER_MIRRORSERVER_TYPE: gitea
      STARHUB_SERVER_MIRRORSERVER_HOST: http://${SERVER_DOMAIN}/gitserver
      STARHUB_SERVER_MIRRORSERVER_USERNAME: root
      STARHUB_SERVER_MIRRORSERVER_PASSWORD: password123
      OPENCSG_ACCOUNTING_NATS_URL: nats://natsadmin:gALqqbP6SpftVdFzrU2URJ8k1G@natsmaster:4222
      OPENCSG_ACCOUNTING_SERVER_HOST: http://account_server
      OPENCSG_ACCOUNTING_SERVER_PORT: 8086
    ports:
      - "8080:8080"
    restart: always
    networks:
      - opencsg


  gitea:
    image: opencsg/csghub-git:latest
    depends_on:
      - postgres
    environment:
      - GITEA_ROOT_URL=http://${SERVER_DOMAIN}/gitserver
      - GITEA_DOMAIN=${SERVER_DOMAIN}/gitserver
      - GITEA_SSH_DOMAIN=${SERVER_DOMAIN}
      - GITEA_HTTP_PORT=3001
      - GITEA_SSH_LISTEN_PORT=2222
      - GITEA_ADMIN_USER=root
      - GITEA_ADMIN_PASSWORD=password123
      - GITEA_ADMIN_EMAIL=root@opencsg.com
      - GITEA_DATABASE_TYPE=postgres
      - GITEA_DATABASE_HOST=postgres
      - GITEA_DATABASE_PORT_NUMBER=5432
      - GITEA_DATABASE_NAME=gitea
      - GITEA_DATABASE_USERNAME=postgres
      - GITEA_DATABASE_PASSWORD=sdfa23Sh!322
      - GITEA_DATABASE_SSL_MODE=disable
      - GITEA_APP_NAME=git
      - GITEA_SMTP_ENABLED=false
      - BITNAMI_DEBUG=true
      - GITEA_LFS_ROOT_PATH=/opt/bitnami/gitea/data/lfs
      - GITEA_LFS_START_SERVER=true
      - GITEA_LFS_STORAGE_TYPE=minio
      - GITEA_LFS_MINIO_ACCESS_KEY_ID=admin
      - GITEA_LFS_MINIO_SECRET_ACCESS_KEY=Password_123
      - GITEA_LFS_MINIO_ENDPOINT=minio:9000
      - GITEA_LFS_MINIO_BUCKET=opencsg-server-lfs
      - GITEA_LFS_MINIO_LOCATION=cn-beijing
      - GITEA_LFS_MINIO_USE_SSL=false
      - GITEA_SERVICE_DEFAULT_ALLOW_CREATE_ORGANIZATION=true
      - GITEA_SERVICE_DISABLE_REGISTRATION=false
    ports:
      - "3001:3001"
      - "2222:2222"
    healthcheck:
      test: curl -fSs 127.0.0.1:3001/api/healthz || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - opencsg
    privileged: true
    restart: always

  minio:
    image: bitnami/minio:2023
    ports:
      - "9000:9000" # api
      - "9001:9001" # console
    environment:
       MINIO_ROOT_USER: admin
       MINIO_ROOT_PASSWORD: Password_123
       MINIO_DEFAULT_BUCKETS: opencsg-server-lfs:public,opencsg-portal-storage:public
       MINIO_SCHEME: http
    volumes:
      - minio_data:/bitnami/minio/data
    networks:
      - opencsg

  natsmaster:
    image: opencsg/csghub-nats:2.10.16
    ports:
      - "4222:4222" # api
      - "6222:6222" # cluster
      - "8222:8222" # monitor
    restart: always
    networks:
      - opencsg

  account_server:
    image: opencsg/csghub-server:v0.7.0
    entrypoint:
      - /starhub-bin/starhub
      - accounting
      - launch
    depends_on:
      - natsmaster
    environment:
      STARHUB_SERVER_API_TOKEN: ${HUB_SERVER_API_TOKEN:-c7ab4948c36d6ecdf35fd4582def759ddd820f8899f5ff365ce16d7185cb2f609f3052e15681e931897259872391cbf46d78f4e75763a0a0633ef52abcdc840c}
      STARHUB_DATABASE_DSN: postgresql://postgres:sdfa23Sh!322@postgres:5432/starhub_server?sslmode=disable
      OPENCSG_ACCOUNTING_SERVER_PORT: 8086
      OPENCSG_ACCOUNTING_NATS_URL: nats://natsadmin:gALqqbP6SpftVdFzrU2URJ8k1G@natsmaster:4222
      OPENCSG_ACCOUNTING_FEE_EVENT_SUBJECT: "accounting.fee.>"
      OPENCSG_ACCOUNTING_NOTIFY_NOBALANCE_SUBJECT: "accounting.notify.nobalance"
      OPENCSG_ACCOUNTING_MSG_FETCH_TIMEOUTINSEC: 5
      OPENCSG_ACCOUNTING_CHARGING_ENABLE: true
      GIN_MODE: release
    ports:
      - "8086:8086"
    restart: always
    networks:
      - opencsg
networks:
  opencsg:
    driver: bridge

volumes:
  minio_data:
    driver: local
