- name: 'hami_institute'
  logo: 'computing/partners/hami_institute.png'
  level: '银牌可信智算合作伙伴'
  sort: 3
- name: 'china_unicom'
  logo: 'computing/partners/china_unicom.png'
  level: '金牌可信智算合作伙伴'
  sort: 2
- name: 'china_telecom'
  logo: 'computing/partners/china_telecom.png'
  level: '金牌可信智算合作伙伴'
  sort: 2
- name: 'enflame'
  logo: 'computing/partners/enflame.png'
  level: '金牌可信智算合作伙伴'
  sort: 2
- name: 'xing_nuan_yun'
  logo: 'computing/partners/xing_nuan_yun.png'
  level: '银牌可信智算合作伙伴'
  sort: 3
- name: 'suanova'
  logo: 'computing/partners/suanova.png'
  level: '银牌可信智算合作伙伴'
  sort: 3
- name: 'ixmission'
  logo: 'computing/partners/ixmission.png'
  level: '银牌可信智算合作伙伴'
  sort: 3
- name: 'xiyunsuanli'
  logo: 'computing/partners/xiyunsuanli.png'
  level: '银牌可信智算合作伙伴'
  sort: 3