- name: 'hami_institute'
  logo: 'computing/partners/hami_institute.png'
  level: '金牌可信智算合作伙伴'
  sort: 2
- name: 'china_unicom'
  logo: 'computing/partners/china_unicom.png'
  level: '银牌可信智算合作伙伴'
  sort: 3
- name: 'china_telecom'
  logo: 'computing/partners/china_telecom.png'
  level: '银牌可信智算合作伙伴'
  sort: 3
- name: 'enflame'
  logo: 'computing/partners/enflame.png'
  level: '银牌可信智算合作伙伴'
  sort: 3