- name: Datawhale
  site: https://datawhale.club/#/
  tags: 开源社区
  desc: Datawhale成立于2018年，是国内头部的开源学习组织，汇聚了来自伯克利、斯坦福、港中文、港科大、清华、北大、上交、复旦、浙大等全球近百所高校的成员，吸引了数十万的AI领域学习者关注；组织以for the learner为使命，致力于构建开源学习社区，和学习者一起成长。
  logo: 'partners/datawhale.png'
- name: Xorbits
  site: https://xorbits.cn
  tags: 算力服务
  desc: 杭州未来速度科技有限公司（简称Xorbits）是⼀家专注于企业级数据和AI的基础设施平台公司，致⼒于研发能够满⾜客户不断增⻓的计算需求的解决⽅案。⽆论是⼤数据分析、⼤模型应⽤，我们的基础设施都能够提供稳定、⾼性能的⽀持，并随着您的业务规模扩⼤⽽轻松扩展。未来速度旗下有两款产品，企业⼤规模处理数据套件Xorbits，对数据处理和AI领域的 Python 库进⾏了加速，如NumPy、pandas和scikit-learn，可轻松扩展到成千台机器，⽀持处理TB级数据；⾼性能⼤模型推理引擎Xinference，提供⼀站式“模型即服务”解决⽅案，针对底层硬件的⾼效适配，⼤幅降低⼤模型的部署⻔槛和成本，助⼒上层 AI 应⽤实现。主要团队成员来⾃阿⾥云、百度、华为和微软，在Data&AI领域有丰富技术实践经验。
  logo: 'partners/xorbits.png'
- name: 浪潮
  site: https://www.inspur.com
  tags: 数据服务,云计算
  desc: 浪潮集团有限公司，即浪潮集团，是中国本土顶尖的大型IT企业之一，中国领先的云计算、大数据服务商。浪潮集团旗下拥有浪潮信息、浪潮软件、浪潮国际三家上市公司，业务涵盖云计算、大数据、工业互联网等新一代信息技术产业领域，为全球120多个国家和地区提供IT产品和服务，浪潮致力于成为世界一流的新一代信息技术产业龙头企业，经济社会数字化转型的优秀服务商，新型基础设施建设的骨干企业。
  logo: 'partners/lang_chao.png'
- name: AWS
  site: https://aws.amazon.com/
  tags: 云计算
  desc: 亚马逊网络服务(AWS)是世界上最全面和最广泛采用的云，从全球数据中心提供200多种功能齐全的服务。数以百万计的客户——包括发展最快的初创公司、最大的企业和领先的政府机构——正在使用AWS来降低成本、变得更敏捷、更快地创新。
  logo: 'partners/aws.png'
- name: NVIDIA
  site: https://www.nvidia.cn
  tags: 算力服务
  desc: NVIDIA 率先推出加速计算来应对其他公司无法解决的挑战。我们在人工智能和数字孪生领域的工作正在改变世界上最大的行业并深刻影响社会。
  logo: 'partners/nvidia.png'
- name: 庖丁科技
  site: https://www.paodingai.com
  tags: 文档智能
  desc: 庖丁科技成立于 2017 年，是“文档智能”领域的领航者，提供从基座、审核、撰写到开发工具的全流程文档处理 SaaS 服务和企业级应用。扎根于金融行业，专注于监管科技，解决金融行业在文档处理方面的风控和效率问题；并依托文档智能的开发工具，培育其它行业的应用生态。公司自成立以来，已申请多项国内外人工智能领域的专利及软著。现阶段客户包括港交所、深交所、中信证券、华泰联合证券、中国银行等 60 多家大型机构，覆盖金融监管、银行、券商、基金、会计师事务所等多个行业
  logo: 'partners/pao_ding.png'
- name: Microsoft
  site: https://www.microsoft.com
  tags: 软件服务
  desc: 微软（Microsoft）是一家美国跨国科技企业，1975年4月4日创立。2023财年营收2119.15亿美元，公司总部设立在华盛顿州雷德蒙德，以研发、制造、授权和提供广泛的电脑软件服务业务为主。最为著名和畅销的产品为Windows操作系统和Office系列软件，是全球最大的电脑软件提供商、世界PC（Personal Computer，个人计算机）软件开发的先导。
  logo: 'partners/microsoft.png'
- name: 中国信通院
  site: http://www.caict.ac.cn
  tags: 指导单位
  desc: 中国信息通信研究院（简称“中国信通院”）始建于1957年，是工业和信息化部直属的科研事业单位。多年来，中国信通院始终秉持“国家高端专业智库 产业创新发展平台”的发展定位和“厚德实学、兴业致远”的核心文化价值理念，在4G/5G、工业互联网、移动互联网、智能制造、物联网、云计算、大数据、人工智能、VR/AR、网络与信息安全等领域进行了深入研究与前瞻布局，在行业发展的重大战略、规划、政策、标准和测试认证等方面发挥了有力支撑作用，为我国通信业跨越式发展和信息技术产业创新壮大起到了重要推动作用。
  logo: 'partners/xin_tong_yuan.png'
- name: 精容数安
  site: https://www.jingrongshuan.com
  tags: 数据安全
  desc: 精容数安成立于2010年，拥有20余年的管理和技术团队。公司以数据安全和数据管理为主线，建立了数据安全全生命周期产品线，保护用户数字资产，助力用户构建完善、可靠的数据安全系统。覆盖全国省会城市20+，合作伙伴8000+。产品包括数据备份与恢复系统、数据库复制软件等，已获得8000+客户的认可。
  logo: 'partners/runstor.png'
- name: 南京航空航天大学
  site: https://www.nuaa.edu.cn
  tags: 高校组织
  desc: 南京航空航天大学（Nanjing University of Aeronautics and Astronautics），简称南航（NUAA），位于江苏省南京市，是中华人民共和国工业和信息化部直属的一所具有航空航天民航特色、以理工类为主的综合性全国重点大学，由工业和信息化部、教育部、江苏省共建， 是国家“双一流”， “211工程”、“985工程优势学科创新平台”重点建设高校，入选“111计划”、卓越工程师教育培养计划、国家建设高水平大学公派研究生项目、新工科研究与实践项目、中国政府奖学金来华留学生接收院校、全国深化创新创业教育改革示范高校、国家大学生文化素质教育基地，中国高校行星科学联盟、中俄交通大学联盟成员。
  logo: 'partners/nan_jing_hang_kong.png'
- name: 清昴智能
  site: https://tsingmao.com
  tags: 云计算
  desc: 清昴智能是 一家Al模型推理部署解决方案提供 商，旨在为各行业客户提供顶尖的Al 优化和工程化能力，解决复杂Al模型的落地难，资源耗费高等问题。创始团队来自于清华大学计算机系，在模型自动优化方向有十余年积累，清昴己发布面向基础模型的自研工具链MLGuide，弥补高性能A推理优化工具的空白，致力于大模型的高速高效落地，帮助客户完成智能化升级
  logo: 'partners/qing_mao.png'
- name: 燧原科技
  site: https://www.enflame-tech.com
  tags: 算力服务
  desc: 上海燧原科技有限公司（燧原科技）是一家专注人工智能领域云端算力平台的创业公司，致力为人工智能产业发展提供普惠的基础设施解决方案，提供自主知识产权的高算力、高能效比、可编程的通用人工智能训练和推理产品。其创新性架构、互联方案和分布式计算及编程平台，可广泛应用于云数据中心、超算中心、互联网、金融及智慧城市等多个人工智能场景。
  logo: 'partners/enflame.png'
- name: KubeSphere
  site: https://kubesphere.com.cn
  tags: 云原生,算力服务,云计算
  desc: KubeSphere 是领先的云原生核心服务商青云科技于 2018 年推出的容器管理平台，致力于打造⼀个以 Kubernetes 为内核的云原⽣分布式操作系统，帮助企业快速构建健壮的容器云平台。目前，KubeSphere 逐步打造了完善的企业级云原生产品家族，包括 KubeSphere 企业版 、KSV 云原生虚拟化、KubeSphere Cloud 云原生应用服务平台、RadonDB 云原生数据库等，并已服务来自金融、运营商、制造、能源、物流、教育等领域的上百家企业客户。
  logo: 'partners/kubesphere.png'
- name: 南方科技大学
  site: https://www.sustech.edu.cn
  tags: 高校组织
  desc: 南方科技大学（Southern University of Science and Technology），简称“南科大”，位于广东省深圳市，是国家“双一流”建设高校、国家高等教育综合改革试验校、广东省高水平理工科大学、广东省高水平大学，入选深圳国际友好城市大学联盟、深圳高校创新创业教育联盟，是深圳市在中国高等教育改革发展的时代背景下创建的一所公办新型研究型大学。
  logo: 'partners/nan_fang_ke_ji.png'
- name: 猴子无限
  site: https://frame.infmonkeys.com
  tags: 大模型
  desc: 猴子无限是一家生成式AI赛道的创业公司，专注于模型调优。通过可控内容生成、模型调优、多模态工作流编排形成应用的方式，弥合营销、游戏领域中，通用大模型到企业落地之间的鸿沟。
  logo: 'partners/hou_zi_wu_xian.png'
- name: 智用人工智能应用研究院
  site:
  tags: 人工智能
  desc: 智用是国内首家立足于人工智能应用的商业型研究院，也是一家专注于人工智能的创新机构，聚焦AI技术、工业元宇宙及部分面向未来大计算基础架构的硬科技与前沿科技发展中的产业应用转化，打通从研究院到市场的转化路径。
  logo: 'partners/zhi_yong.png'
- name: 乐讯科技
  site: http://www.lexun.cn
  tags: 算力服务
  desc: 深圳市乐讯科技有限公司是国内领先的移动社区运营企业，旗下的乐讯科技社区网站自2004年8月创立以来，以其开放包容的特色受到了广大手机用户的推崇，产品内容丰富，包括圈子，聊天室，小频道等社交类应用，也推出了以休闲小游戏为主的乐游平台，同时未来将在中轻度的手游产品上发力，为手机用户打造一个综合性社交娱乐平台。
  logo: 'partners/le_xun.png'
- name: Pleisto
  site:
  tags: 软件服务
  desc: Pleisto 是一家科技初创公司，专注于利用 AI 赋能传统行业的软件开发。作为""开发者背后的开发者""，Pleisto 的核心产品Flappy是一个专为真实生成环境设计的大模型应用开发框架。其目标是弥合大型语言模型与开发者之间的鸿沟，使得不具备 AI 背景的传统软件开发者能够开发行业 AI 应用。此外，Pleisto同时致力于为企业客户提供行业 AI 落地的全流程解决方案，提供合规的行业垂直模型的定制开发与技术咨询服务。目前，Pleisto 是负责制定全球 web 标准的国际组织——世界万维网联盟（W3C）的成员单位。
  logo: 'partners/pleisto.png'
- name: 云上曲率
  site: https://www.ilivedata.com/
  tags: 人工智能
  desc: 北京云上曲率科技有限公司（简称云上曲率）是一家全球实时互动与人工智能解决方案服务商，为全球企业及开发者提供稳定可靠、性能卓越的实时互动、多语言内容风控、智能翻译服务，致力于为全球用户提供稳定、安全、无界的一站式实时互动体验。
  logo: 'partners/yun_shang_qu_lv.png'
- name: 即算科技
  site: https://www.hpc-now.com
  tags: 云计算
  desc: 上海即算科技有限公司是一家专注于科研工程高性能计算的创新企业。公司自主研发大规模并行计算平台、AI 服务平台等一系列云计算产品，并深入了解教育、科研、工程在不同场景下的业务需求， 提供公有云、混合云、私有云、专有云在内的“一站式”高性能计算解决方案。即算科技核心团队来自腾讯、阿里、华为、AWS 等国内外知名互联网和IT 企业，除此之外，有来自哈尔滨工业大学、西北工业大学等国内顶尖高校中的流体、物理、化学、气象、生物等相关行业人才。即算科技专注于计算本身，旨在提供更优质的高性能计算服务和平台， 助推各行业科技创新、攀登技术高峰。
  logo: 'partners/ji_suan.png'
- name: 奥朗科技
  site: https://www.sretraining.cn
  tags: AIOps,人工智能培训
  desc: 上海奥朗信息科技有限公司（简称：雅菲奥朗），雅菲奥朗是国内知名的 AIOps(人工智能运维)培训和咨询公司，是大中国区第一批 SRE 和 AIOps 的实践者与引领者，并获得国际认证机构的中国区唯一授权人工智能（AIOps）培训资质。雅菲奥朗承“知识创新、智能创新、实践创新”的核心理念，基于在多家知名企业的 AI 成功落地经验，持续引入国际先进的理念和方法论，并结合中国实际情况进行深度创新，我们拥有独创的培训和咨询方法论。雅菲奥朗致力于培养与时俱进的科技创新人才，专注于“互联网和人工智能时代”的 AI 培训与咨询，我们帮助企业进行数字化转型，持续提升科技管理能力，赶超世界先进水平。
  logo: 'partners/ao_lang_ke_ji.png'
- name: DaoCloud 道客
  site: https://www.daocloud.io
  tags: 云原生
  desc: 「DaoCloud 道客」云原生领域的创新领导者，成立于 2014 年底，拥有自主知识产权的核心技术，致力于打造开放的云操作系统为企业数字化转型赋能。产品能力覆盖云原生应用的开发、交付、运维全生命周期，并提供公有云、私有云和混合云等多种交付方式。成立迄今，公司已在金融科技、先进制造、智能汽车、零售网点、城市大脑等多个领域深耕，标杆客户包括交通银行、浦发银行、上汽集团、东风汽车、海尔集团、屈臣氏、金拱门（麦当劳）等。目前，公司已完成了 D 轮超亿元融资，被誉为科技领域准独角兽企业。公司在北京、南京、武汉、深圳、成都设立多家分公司及合资公司，总员工人数超过 350 人，是国家级“专精特新”小巨人企业、上海市高新技术企业、上海市 “科技小巨人” 企业和上海市 “专精特新” 企业，并入选了科创板培育企业名单。
  logo: 'partners/dao_cloud.png'
- name: 瀚诚软件
  site: https://www.highsoft.ltd
  tags: 敏捷开发
  desc: 瀚诚软件致力于通过高度定制化的软件交付和咨询服务，帮助广大企业客户解决企业IT能力与业务需求的错配问题。瀚诚软件以极限编程为核心实践，擅长通过敏捷方法为客户的创新型产品提供专业的IT服务与保障。
  logo: 'partners/han_cheng_ruan_jian.png'
- name: 寒武纪
  site: https://www.cambricon.com
  tags: 人工智能芯片
  desc: 寒武纪成立于2016年，专注于人工智能芯片产品的研发与技术创新，致力于打造人工智能领域的核心处理器芯片，让机器更好地理解和服务人类。寒武纪提供云边端一体、软硬件协同、训练推理融合、具备统一生态的系列化智能芯片产品和平台化基础系统软件。寒武纪产品广泛应用于服务器厂商和产业公司，面向互联网、金融、交通、能源、电力和制造等领域的复杂 AI 应用场景提供充裕算力，推动人工智能赋能产业升级。
  logo: 'partners/han_wu_ji.png'
- name: OpenTEKr
  site: https://www.opentekr.com
  tags: 开源社区
  desc: OpenTEKr是一个以推广开源理念和发展各类开源应用为核心的社区，专注开源与产业的融合及开源与商业的实践，推动开源产业化。社区层面：OpenTEKr联合各类开源组织，机构和开源爱好者进行开源理念的宣传和普及，开源原创内容的制作和推广，开源活动的策划和开展，开源技术的集成与融合应用商业层面; OpenTEKr和各类开源贡献方，使用方及参与方开展各类商业合作，服务各开源社区更好的开展开源活动，服务各开源使用方更好的使用开源。主要业务有 1） 企业开源赋能服务包含开源教育，治理咨询，数字化转型应用建设； 2） 开源社区赋能服务包含开源战略，开源运营，技术工程化； 3） 开源人赋能成长：培训，认证，职业机会；
  logo: 'partners/open_tekr.png'
- name: OSCHINA
  site: https://www.oschina.net
  tags: 开源社区
  desc: 开源中国（OSCHINA，Open Source China，OSC）成立于 2008 年 8 月，是国内知名的开源技术社区，建立了完善的开源软件分类数据库，收录全球知名开源项目近 10 万款，涉及几百个不同的分类 。围绕这些开源项目，OSCHINA 为中国开发者提供了开源资讯、软件更新资讯、技术分享和交流的技术平台。2013 年，OSCHINA 建立了企业级研发效能平台、基于 Git 的代码托管平台“码云 Gitee”，为广大开发者提供团队协作、源码托管、代码质量分析、代码评审、测试、CI/CD 与代码演示等功能。经过在开源领域超过十年的深耕，以及与中国本土开源环境的结合，OSCHINA 推动了中国开源领域的快速发展。OSCHINA 社区有 600 万开发者活跃，长期致力于推动国内开源软件的应用和发展，提升本土开源能力，以及为开源生态环境的优化提供支持。
  logo: 'partners/os_china.png'
- name: 睿思芯科
  site: https://rivai-ic.com.cn/
  tags: 人工智能芯片
  desc: 睿思芯科成立于2018年底，是一家提供 RISC-V 高端核心处理器解决方案的公司，创始团队来自于加州大学伯克利分校 RISC-V 原创项目组。公司主要开发基于 RISC-V 的高性能处理器 IP 核，提供垂直领域（DSA）定制处理器设计服务以及定制芯片解决方案，满足从边缘计算到数据中心等各领域的高算力要求，客户涵盖国内外多家知名企业，开展 IP 授权和 SoC 定制化开发合作。
  logo: 'partners/rui_si_ke_ji.png'
- name: 始智AI-wisemodel社区
  site: https://www.wisemodel.cn
  tags: 开源社区
  desc: 始智AI-wisemodel-中国AI开源创新社区
  logo: 'partners/shi_zhi_ai.png'
- name: 中国SRE社区
  site: https://www.srenow.cn/news.html
  tags: 生态社区
  desc: SRE专委会（又名“中国SRE社区”），于2021年4月，正式登记为中关村人才协会下的“SRE专委会”专业机构。对外交流时，也常称为“中国SRE社区”和“中国SRE书友会”。SRE作为新兴的互联网和云运维学科，在国际和国内都享有崇高的美誉度和公认的创新价值。为了将SRE先进理念引入中国，并推动在中国国内的传播和实践。中国SRE社区创始人牵头从2018年起创办基于互联网（腾讯云课堂）的“中国SRE书友会”，持续将谷歌SRE先进技术和管理实践引入国内 。经过3年的积累和沉淀，中国SRE社区的公益实践（包括读书分享、互联网研讨会、学术专著引入和翻译等）获得社会的广泛认可。中国SRE社区于2021年4月，正式登记为中关村人才协会下的“SRE专委会”专业机构。
  logo: 'partners/sre_community.png'
- name: 云辉中创
  site:
  tags: DevOps
  desc: 云辉中创成立于2018年，总部位于中国北京。云辉中创是一家数字化转型和DevOps解决方案提供商，旨在帮助客户实现数字化转型，以达成商业目标。我们提供完整的数字化转型方案和高效便捷的DevOps解决方案，让客户可以更好地应对业务挑战和市场变化。我们的团队拥有丰富的经验和专业知识，能够根据客户需求量身定制解决方案，确保客户获得最佳的服务和体验。
  logo: 'partners/yun_hui_zhong_chuang.png'
- name: 云轴科技
  site: https://www.zstack.io
  tags: 云计算,云原生
  desc: 上海云轴信息科技有限公司（ZStack）成立于2015年，现有员工500+人，是产品化的云基础软件提供商，国家级高新技术企业，国家级专精特新“小巨人”。公司创始团队由国内虚拟化、云计算领域的“黄金一代”组成，先后获得阿里云、中国电信战略投资，2023年4月完成由国鑫创投、君联资本领投的C轮融资。ZStack产品矩阵全面覆盖数据中心云基础设施，涵盖云平台/虚拟化、分布式存储、容器云平台、多云管理平台、超融合一体机、云原生超融合、数据库云平台等产品线。ZStack自研架构，自主知识产权，独立于VMware和OpenStack技术路线；坚持产品化道路，轻量级部署，一云八芯，全面适配，在同等环境下获云计算性能测试国际标准SPEC Cloud全球第一。ZStack全球广泛部署，企业级客户众多。公司总部位于上海，在北京、成都、广州、武汉、杭州、厦门、南京、西安、合肥、济南、深圳、香港等地设立分公司和办事处，服务全国34个省市自治区，部署信创云400+朵，助力3000+家企业级用户实现数字化转型。ZStack实现规模出海，携手300+家活跃渠道和200+家生态伙伴，覆盖全球30+个国家和地区，涵盖政府、通信、金融、能源、交通、医疗、教育、制造等10+个行业领域。
  logo: 'partners/yun_zhou_ke_ji.png'
- name: reInventAI
  site:
  tags: 人工智能,大模型
  desc: reInventAI是一家人工智能基础大模型开发商，专注于基础模型和通用人工智能（AGI），旨在打造面向行业的专业大模型。致力于打造领先的SOTA（state-of-the-art）基础模型，并且将为行业开发可信赖、高性能的垂直模型。对于部分行业，公司不仅提供可直接使用的预训练行业基础模型，还支持企业客户根据自身需求进一步定制专属基础模型。
  logo: 'partners/relnvent_ai.png'
- name: 博云
  site:
  tags: 云原生,AI基础软件,私有训推平台
  desc: 江苏博云科技股份有限公司（简称：博云）是国内云原生基础软件领域的创新领导者，是国家高新技术企业，国家级专精特新小巨人企业。公司专注为企业级客户提供自主可控，以容器和云资源调度技术为基础的云操作系统相关的基础设施软件、解决方案与技术服务，包括人工智能基础设施产品族、容器云产品族、云资源管理系统、开发支撑软件DevOps四大系列产品与服务。公司充分利用自身在云原生领域的长期技术积累，为企业提供云原生架构下的高弹性、高可用、高安全性的人工智能开发基础设施和算力运营基础设施，实现对 AI 计算资源的灵活调度、远程共享等目标，支持千卡万核的大模型训练迭代和算力资源运营，帮助企业提升人工智能时代的企业竞争力。
  logo: 'partners/boyun.png'