test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

aliyun_staging:
  service: Aliyun
  access_key_id: <%= Rails.application.credentials.s3.staging[:access_id] %>
  access_key_secret: <%= Rails.application.credentials.s3.staging[:access_secret] %>
  bucket: <%= Rails.application.credentials.s3.staging[:bucket_name] %>
  endpoint: <%= Rails.application.credentials.s3.staging[:endpoint] %>
  # path prefix, default: /
  path: "active_storage"
  # Bucket public: true/false, default: true, for generate public/private URL.
  public: false

aliyun:
  service: Aliyun
  access_key_id: <%= Rails.application.credentials.s3.production[:access_id] %>
  access_key_secret: <%= Rails.application.credentials.s3.production[:access_secret] %>
  bucket: <%= Rails.application.credentials.s3.production[:bucket_name] %>
  endpoint: <%= Rails.application.credentials.s3.production[:endpoint] %>
  # path prefix, default: /
  path: "active_storage"
  # Bucket public: true/false, default: true, for generate public/private URL.
  public: false
